#to apply this file we will use a command
#kubectl apply -f nameoftheyaml file
apiVersion: apps/v1
kind: Deployment

metadata: 
  name: myapp3-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp3

  template:
    metadata:
      name: myapp3-pod
      labels:
        app: myapp3
    spec:
      containers:
      - name: myapp3-container
        image: stacksimplify/kubenginx:3.0.0
        ports:
          - containerPort: 80
